# This file is used to define a custom transformers for our CRDs so that Kustomize
# can resolve the cross-resource object references.
# See https://github.com/kubernetes-sigs/kustomize/blob/master/examples/transformerconfigs/crd/README.md

# nameReference is used to declare which kind's name is referred in which resources.
nameReference:
  - kind: Network
    fieldSpecs:
      - path: spec/to/base/spec/forProvider/settings/ipConfiguration/privateNetworkRef/name
        kind: Composition
  - kind: Provider
    fieldSpecs:
      - path: spec/to/base/spec/providerRef/name
        kind: Composition

# varReference is the list of fields that we tell Kustomize to process for
# variants.
varReference:
  - path: spec/to/base/spec/forProvider/region
    kind: Composition
